### ISSUE TITLE
Lerna 2.0.0 Performance Issues

### ISSUE THREAD

**Issue by ianwremmel** [kittens/lerna#109]
Lerna 2.x seems to run much more slowly than 1.x on an already fully bootstrapped install. The following output is for babel's master branch.

```bash
$ node --version
v4.3.0
$ npm --version
2.14.12

$ time ./node_modules/.bin/lerna bootstrap

Lerna bootstrap v1.1.2

Current version: 6.7.6
Version file location: /Users/ian/projects/babel/VERSION
Packages location: /Users/ian/projects/babel/packages

Successfully bootstrapped 118 packages.


real	0m31.458s
user	1m25.776s
sys	0m11.374s

$ time ./node_modules/.bin/lerna bootstrap
Lerna bootstrap v2.0.0-beta.3
Successfully bootstrapped 118 packages.

real	2m4.354s
user	4m38.900s
sys	1m18.930s
```

**Comment by hzoo** [comment]
Thanks for the issue! We aren't using lerna 2 on babel yet. Also you are running on npm 2 (we develop with npm 3 and recommend that for babel 6)

**Comment by ianwremmel** [comment]
I tried npm 3 with my own repo (which I can't share yet) this weekend and it had similar results.

**Comment by thejameskyle** [comment]
Oh I know why it's slower.

We're now doing:

```js
npm install external-package-1@1.0.0 external-package-2@1.0.0
```

Instead of just `npm install`, so npm is fetching them every single time. This is likely even worse in npm 2.

We need to be explicit in what packages we install because otherwise it causes issues with local packages that you have not published yet.

npm really should not be fetching anything if the version you are asking to be installed is already installed, but we could also check for that on our end

**Comment by thejameskyle** [comment]
Moving to #125
