### ISSUE TITLE
Should lerna bootstrap install deps individually

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#79]
Right now we're just executing `npm install` in each package directory. However, because of the "linked" dependencies, we have an order of operations issue, either [we end up installing over the linked dependencies](https://github.com/kittens/lerna/pull/31) or we try [installing dependencies that do not exist](https://github.com/kittens/lerna/issues/59).

A possible solution to this might be manually writing out what we want to install:

```json
{
  "dependencies": {
    "a": "1.0.0",
    "b": "2.0.0"
  }
}
```

```sh
$ npm install a@1.0.0 b@2.0.0
```

This might fix #59. Also I wonder if this will make npm any faster because we're explicitly asking it for things, probably not, but maybe.

**Comment by evocateur** [comment]
The versions (`foo@1.0.0`) aren't necessary in this form (`npm i foo bar baz...`), because npm recognizes they are in the package.json and uses the version range specified there. In other words, if `"glob": "^6.0.0"` is specified in dependencies, `npm i glob` will always install `glob@^6.0.0`.

As for speed, the only gains I can think of would be the omission of the dependencies unique to the local packages, and those are probably minimal at best. Regardless, this sounds like a good way to fix #59. I'll take a crack at it later today.
