### ISSUE TITLE
Should major releases update all packages?

### ISSUE THREAD

**Issue by cpojer** [kittens/lerna#94]
I updated my packages from 9.0.x to 10.0.0 today and noticed only some of my packages were updated (the ones changed since the last publish, which didn't use lerna yet). I feel like that makes sense for patch and minor releases, but for majors it probably makes sense to publish all packages and update all dependencies – otherwise I can imagine that it is going to give some headaches.

What do you think?

**Comment by hzoo** [comment]
Hey @cpojer! We haven't really used lerna with a major version yet so we are still figuring it out as well. Currently it's doing a git diff against files since the last tag.

Right now you can force a version by passing in `FORCE_VERSION=*` in process.env before running (https://github.com/kittens/lerna/blob/1.x/lib/commands/updated.js#L50)

Also, you are using 1.x right (published 2.x as a prerelease).

**Comment by thejameskyle** [comment]
Yeah, we should be recursively look up dependents of changed packages to prompt for version bumps. I'll try doing that now

**Comment by thejameskyle** [comment]
Lerna will now include all cross-dependencies when publishing, if you want to force a new version for absolutely everything you can also use `FORCE_VERSION=* lerna publish`. Note that I'm going to make that `lerna publish --force-version *` in the next beta release.
